#!/usr/bin/env bash
# Render the k8s/observability overlay's generated files from the sources under observability/.
#
#   scripts/render-k8s-observability.sh     rewrite the generated files, say which ones changed
#
# The overlay has to carry the alert rules and the dashboards a second time, because Kustomize
# refuses to reference a file outside the kustomization's own directory -- `../../observability`
# is an error, not a shortcut -- so a PrometheusRule and two dashboard ConfigMaps must contain
# what Compose mounts. Two copies of a file drift; this script is what makes re-syncing them
# one command, and ObservabilityManifestsTest is what makes forgetting to run it a red build
# rather than a threshold that differs between Compose and the cluster.
#
# Nothing here parses YAML or JSON, on purpose. The rules file is `groups:` at the top level,
# so indented under `spec:` it is the PrometheusRule's spec verbatim, comments included; a
# dashboard indented under a block scalar is a ConfigMap's file content. sed is the only tool,
# so the output is the same on every machine and does not depend on a yq or a PyYAML being
# installed -- and there is no serializer to reorder keys or reflow strings on the way through.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
SRC=$ROOT/observability
OUT=$ROOT/k8s/observability
NS=ai-customer-service

# Indent every non-empty line; blank lines stay blank rather than gaining trailing spaces.
indent() { sed -e "/./s/^/$1/"; }

# Write stdin to $1 only if it differs, and say which happened. A file rewritten with the
# same bytes would still show up in an editor's "changed" list for nothing.
place() {
  local target=$1 tmp
  tmp=$(mktemp "${TMPDIR:-/tmp}/render.XXXXXX")
  cat > "$tmp"
  if [[ -f $target ]] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"; printf '  unchanged  %s\n' "${target#"$ROOT"/}"
  else
    mv "$tmp" "$target"; printf '  wrote      %s\n' "${target#"$ROOT"/}"
  fi
}

generated_header() {
  cat <<HEADER
# GENERATED by scripts/render-k8s-observability.sh from $1 -- do not edit this file.
# Edit the source, run the script, and commit both. Kustomize cannot reference a file outside
# its own directory, which is why this is a copy; ObservabilityManifestsTest fails when the copy
# and the source differ.
HEADER
}

echo "rendering into ${OUT#"$ROOT"/}"

rules=observability/prometheus/rules/customer-service.yml
{
  generated_header "$rules"
  cat <<YAML
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: customer-service
  namespace: $NS
  labels:
    app.kubernetes.io/name: ai-customer-service-java
    app.kubernetes.io/component: observability
spec:
YAML
  indent '  ' < "$ROOT/$rules"
} | place "$OUT/prometheus-rule.yaml"

for dashboard in "$SRC"/grafana/dashboards/*.json; do
  file=$(basename "$dashboard")
  name=${file%.json}
  {
    generated_header "observability/grafana/dashboards/$file"
    cat <<YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-$name
  namespace: $NS
  labels:
    app.kubernetes.io/name: ai-customer-service-java
    app.kubernetes.io/component: observability
    # What kube-prometheus-stack's Grafana sidecar watches for; the value is not read.
    grafana_dashboard: "1"
data:
  $file: |
YAML
    indent '    ' < "$dashboard"
  } | place "$OUT/dashboard-$name.yaml"
done
